### ISSUE TITLE
How to split lines in  content of dialogs

### ISSUE THREAD

**Issue by Ofer-Gal** [SPFxAppDev/fluentui-react-controls#1]
Great helper, enjoy using it.
One little issue.
Is there a way for me to have a line break in the content of "ConfirmDialog" and "AlertDialog"?
I tried \n and <br/> but they just show in the text.

Thanks

**Comment by SPFxAppDev** [comment]
Hi @Ofer-Gal 

Thank you for the feedback and use. Currently it is not possible to add a new line. I am using the [subtext property of the dialog "dialogContentProps"](https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog#IDialogContentProps) and this only supports strings. But it is a good idea to add this feature. I will add this feature in the next version

**Comment by SPFxAppDev** [comment]
Hi @Ofer-Gal 

the Version 0.0.10 allows the passing of `string | JSX.Element | (() => JSX.Element)` as value for the `content` attribute/property.

I hope you like it!

**Comment by Ofer-Gal** [comment]
Could you please show example that will show 2 lines?

**Comment by SPFxAppDev** [comment]
Sure:

```typescript
<AlertDialog 
  hidden={!this.state.showAlert} 
  onDismiss={() => {
    this.setState({
      showAlert: false
    });
  }}
 content={(): JSX.Element => {
 return <><div>line 1</div><div>line 2</div></>;
}}
/>
```
