### ISSUE TITLE
options = {some  IDropdownOption[] } causes an error

### ISSUE THREAD

**Issue by Ofer-Gal** [SPFxAppDev/fluentui-react-controls#2]
Seams I am the only one with Issues. :-)
I tried to do something like your big data example but with hooks (the example @fluentui/react is 7.199.1 and I can't change it)

```
import { IDropdownOption } from '@fluentui/react/lib/Dropdown';  ("^8.117.2")
import { SearchableDropDown } from '@spfxappdev/fluentui-react-controls';

//-----------in the React.FC ----------------
  const [crmClients, setcrmClients] = React.useState<IDropdownOption[]>([]);
// in the  React.useEffect(
	setcrmClients( Clients); //Clients come from a function returning  IDropdownOption[] (many items)

// in the Return 
<SearchableDropDown   options={crmClients} />
```

The type script error is:

```
No overload matches this call.
  Overload 1 of 2, '(props: ISearchableDropDownProps | Readonly<ISearchableDropDownProps>): SearchableDropDown', gave the following error.
    Type 'IDropdownOption<any>[]' is not assignable to type 'IDropdownOption[]'.
      Type 'IDropdownOption<any>' is not assignable to type 'IDropdownOption'.
        Types of property 'itemType' are incompatible.
          Type 
```
When I change the array state to be any[] it does not error any more. 

Any way to make it work?

**Comment by SPFxAppDev** [comment]
Hi @Ofer-Gal 

> Seams I am the only one with Issues. :-)

:-D Yeah I think it's because you're one of the first ones who uses my package. :)

I think I need to update the fluent UI version. My SPFx version is 1.17 and it uses the fluent UI 7.199 version by default. The bug is a Fluent UI version conflict, I think. I will change it soon. Thanks for the report!
